create or replace TYPE FS_PCRM_US.EM_TO_EMTP IS

OBJECT (
		TPEM_TPEM	 NUMBER(22),
		TPEM_DTEM	 VARCHAR2(50),
		TPEM_STEM	 VARCHAR2(1), 
		TPEM_FCCR	 DATE,
		TPEM_FCMO	 DATE,
		EMNE_EMNE	 NUMBER(22),
		EMNE_NOBE	 VARCHAR2(100),
		EMNE_NITE	 VARCHAR2(200),
		EMNE_FECR	 DATE,
		EMNE_FEMO	 DATE,
		EMTE_EMTE 	 NUMBER(22),
		EMTE_DTCR	 DATE,
		EMTE_DTMO	 DATE,
		EMTE_TPEM	 NUMBER(22),
		EMTE_EMNE	 NUMBER(22)
		);
		
/