ALTER SESSION SET CURRENT_SCHEMA=PACRIM_US;

@@01_TABLAS\00_INSTALL_TABLAS.sql
@@02_FOREIGN_KEY\00_INSTALL_FOREIGN.sql
@@03_INDICES\00_INSTALL_INDICES.sql
@@04_SECUENCIAS\00_INSTALL_SECUENCIAS.sql
@@05_TIPOS\00_INSTALL_TIPOS.sql
@@06_PAQUETES\00_INSTALL_PAQUETES.sql
@@07_DATOS\00_INSTALL_DATOS.sql