DECLARE
  P_NOMBRE_PAIS VARCHAR2(255);
  P_QUERY_PAIS VARCHAR2(255);
  P_NE_TDENE FS_PCRM_US.NE_TT_NE_TDENE;
  P_COD_RTA VARCHAR2(100);
  P_MSJ_RTA VARCHAR2(256);
BEGIN
  P_NOMBRE_PAIS := 'Colombia';

  PC_API_WEB.CONSULTARDEPARTAMEPAIS(
    P_NOMBRE_PAIS => P_NOMBRE_PAIS,
    P_QUERY_PAIS => P_QUERY_PAIS,
    P_NE_TDENE => P_NE_TDENE,
    P_COD_RTA => P_COD_RTA,
    P_MSJ_RTA => P_MSJ_RTA
  );
DBMS_OUTPUT.PUT_LINE('P_QUERY_PAIS = ' || P_QUERY_PAIS);


IF P_NE_TDENE IS NOT NULL THEN
    DBMS_OUTPUT.PUT_LINE ('departamentos = ' ||P_NE_TDENE.count );
  FOR i IN 1..P_NE_TDENE.count LOOP

    DBMS_OUTPUT.PUT_LINE ('P_NE_TCDNE = ' ||P_NE_TDENE(i).DENE_NAME );
  END LOOP;
END IF;


DBMS_OUTPUT.PUT_LINE('P_COD_RTA = ' || P_COD_RTA);


DBMS_OUTPUT.PUT_LINE('P_MSJ_RTA = ' || P_MSJ_RTA);

--rollback; 
END;
