INSERT INTO "FS_PCRM_US"."EM_TTPEM" (TPEM_TPEM, TPEM_DTEM, TPEM_STEM, TPEM_FCCR) VALUES ('1', 'Provedora', 'A', TO_DATE('2018-03-30 03:26:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "FS_PCRM_US"."EM_TTPEM" (TPEM_TPEM, TPEM_DTEM, TPEM_STEM, TPEM_FCCR) VALUES ('2', 'Directora', 'A', TO_DATE('2018-03-30 03:26:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "FS_PCRM_US"."EM_TTPEM" (TPEM_TPEM, TPEM_DTEM, TPEM_STEM, TPEM_FCCR) VALUES ('3', 'Productora', 'A', TO_DATE('2018-03-30 03:26:10', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO "FS_PCRM_US"."EM_TTPEM" (TPEM_TPEM, TPEM_DTEM, TPEM_STEM, TPEM_FCCR) VALUES ('4', 'Cliente', 'A', TO_DATE('2018-03-30 03:26:10', 'YYYY-MM-DD HH24:MI:SS'));
COMMIT;