INSERT INTO "FS_PCRM_US"."NE_TPRNE" (PRNE_PRNE, PRNE_NMPR, PRNE_DEPR, PRNE_CRPR, PRNE_EMUS, PRNE_INEM, PRNE_TPPR) VALUES ('1', 'EXPIRIA', 'CELULAR SONY BUENO', TO_DATE('2018-03-30 07:54:34', 'YYYY-MM-DD HH24:MI:SS'), '3', '2', '2');
INSERT INTO "FS_PCRM_US"."NE_TPRNE" (PRNE_PRNE, PRNE_NMPR, PRNE_DEPR, PRNE_CRPR, PRNE_EMUS, PRNE_INEM, PRNE_TPPR) VALUES ('2', 'LED SONY', 'PANTALLA LED', TO_DATE('2018-03-30 07:54:34', 'YYYY-MM-DD HH24:MI:SS'), '3', '1', '1');

COMMIT;