INSERT INTO "FS_PCRM_US"."NE_TTPCL" (TPCL_TPCL, TPCL_NRTP, TPCL_DETP, TPCL_DACR) VALUES ('1', 'CLIENTE FISICO', 'UN SER HUMANO', TO_DATE('2018-03-30 08:01:16', 'YYYY-MM-DD HH24:MI:SS'));


INSERT INTO "FS_PCRM_US"."NE_TTPCL" (TPCL_TPCL, TPCL_NRTP, TPCL_DETP, TPCL_DACR) VALUES ('2', 'CLIENTE LOGICO', 'UNA MAQUINA', TO_DATE('2018-03-30 08:01:16', 'YYYY-MM-DD HH24:MI:SS'));


COMMIT;