INSERT INTO "FS_PCRM_US"."NE_TTPPR" (TPPR_TPPR, TPPR_NBTP, TPPR_DETP, TPPR_PRNE) VALUES ('1', 'PANTALLAS', 'TELEVISIORES', '1');
                                                                      
INSERT INTO "FS_PCRM_US"."NE_TTPPR" (TPPR_TPPR, TPPR_NBTP, TPPR_DETP, TPPR_PRNE) VALUES ('2', 'CELULARES', 'TELEFONOS MOBILES', '2');

COMMIT;