INSERT INTO "FS_PCRM_US"."NE_TINEM" (INEM_INEM, INEM_NOIN, INEM_DEIN, INEM_INCR, PVUS_PVUS, EMUS_EMUS) VALUES ('1', 'iNVENTARIO SONY', '50', TO_DATE('2018-03-30 07:41:49', 'YYYY-MM-DD HH24:MI:SS'), '1', '3');

INSERT INTO "FS_PCRM_US"."NE_TINEM" (INEM_INEM, INEM_NOIN, INEM_DEIN, INEM_INCR, PVUS_PVUS, EMUS_EMUS) VALUES ('2', 'iNVENTARIO PACRIM MOBILES', '200', TO_DATE('2018-03-30 07:41:49', 'YYYY-MM-DD HH24:MI:SS'), '2', '3');


COMMIT;