INSERT INTO "FS_PCRM_US"."NE_TTSTC" (TSTC_TSTC, TSTC_NOST, TSTC_DEST, TSTC_DACR, TSTC_CLNE) VALUES ('1', 'ACTIVO', 'CUANDO EL CLIENTE PUEDE OPERAR', TO_DATE('2018-03-30 08:03:29', 'YYYY-MM-DD HH24:MI:SS'), '1');


INSERT INTO "FS_PCRM_US"."NE_TTSTC" (TSTC_TSTC, TSTC_NOST, TSTC_DEST, TSTC_DACR, TSTC_CLNE) VALUES ('2', 'INACTIVO', 'CUANDO EL CLIENTE NO  PUEDE OPERAR', TO_DATE('2018-03-30 08:03:29', 'YYYY-MM-DD HH24:MI:SS'), '1');

COMMIT;