REM ******************************************************************
REM Fecha         : 26/03/2018
REM Realizado por : TheOverLordKotan
REM Base de Datos : FS_PCRM_US
REM ******************************************************************

REM TABLESPACE Y SEGMENTOS DE ROLLBACK
set feedback off
spool TMP.lst
select distinct 'pause DEBE estar conectado con Usuario SYSTEM' || chr(10) || 'ROLL' || chr(10) || 'EXIT'
from dual
where user <> 'SYSTEM'
/
spool off
start TMP.lst
set feedback on

REM USUARIO  DUENHO DEL APLICATIVO PACRIM_US
drop user PACRIM_US cascade;
/

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."EM_TEMNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;  

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."EM_TEMTE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."EM_TTPEM" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TCLNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TEMUS" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TINEM" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TPRNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TPVNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TPVUS" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TTPCL" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TTPNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TTPPR" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TTPPV" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TTRPR" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."NE_TTSTC" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."US_TTPRL" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."US_TUSNE" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

begin
	EXECUTE IMMEDIATE 'DROP TABLE   "FS_PCRM_US"."US_TUSRL" CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN NULL;
end;

REM TABLESPACE DE DATOS
DROP TABLESPACE TS_TPACRIM INCLUDING CONTENTS
/

REM TABLESPACE DE INDICES 
DROP TABLESPACE TS_IPACRIM INCLUDING CONTENTS
/

REM TABLESPACE TEMPORAL
DROP tablespace TS_TPACRIM
/






