/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 07-jun.-2018 5:56:50 p.m. 				*/
/*  DBMS       : Oracle 						*/
/* ---------------------------------------------------- */

/* Drop Tables */


CREATE TABLE  "FS_PCRM_US"."NE_TCDNE"
(
	"CDNE_CDNE" NUMBER(22) NOT NULL,    -- Identificador unico del estado de negocio 
	"CDNE_LTUD" NUMBER(10,8) NULL,
	"CDNE_LOTD" NUMBER(11,8) NULL,
	"CDNE_NAME" VARCHAR2(255) NULL,
	"DENE_DENE" NUMBER(22) NULL,
	"PSNE_PSNE" NUMBER(22) NULL
)
TABLESPACE	TS_PACRIM
PCTFREE		10
INITRANS	1
MAXTRANS	255
STORAGE (
	INITIAL		65536
	MINEXTENTS	1
	MAXEXTENTS	2147483645
	BUFFER_POOL	DEFAULT
	)
LOGGING
NOCOMPRESS
NOCACHE
NOPARALLEL
MONITORING
;

/* Create Comments, Sequences and Triggers for Autonumber Columns */

COMMENT ON TABLE  "FS_PCRM_US"."NE_TCDNE" IS 'Tabla que almacena el estado del negocio que tienen los usuarios en las empresas'
;

COMMENT ON COLUMN  "FS_PCRM_US"."NE_TCDNE"."CDNE_CDNE" IS 'Identificador unico del estado de negocio '
;

/* Create Primary Keys, Indexes, Uniques, Checks, Triggers */

ALTER TABLE  "FS_PCRM_US"."NE_TCDNE" 
 ADD CONSTRAINT "PK_NE_TCDNE"
	PRIMARY KEY ("CDNE_CDNE") 
 USING INDEX 
 LOGGING 
 TABLESPACE	TS_IPACRIM 
 PCTFREE		10 
 INITRANS	2 
 MAXTRANS	255 
 STORAGE ( 
	INITIAL		65536
	MINEXTENTS 1
	MAXEXTENTS 2147483645
	BUFFER_POOL DEFAULT 
		)
;


CREATE INDEX "IXFK_NE_TCDNE_NE_TDENE"   
 ON  "FS_PCRM_US"."NE_TCDNE" ("DENE_DENE") 
TABLESPACE	TS_IPACRIM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 128K
    next 1M
    minextents 1
    maxextents unlimited
  );

CREATE INDEX "IXFK_NE_TCDNE_NE_TPSNE"   
 ON  "FS_PCRM_US"."NE_TCDNE" ("PSNE_PSNE") 
TABLESPACE	TS_IPACRIM
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 128K
    next 1M
    minextents 1
    maxextents unlimited
  );

/* Create Foreign Key Constraints */

ALTER TABLE  "FS_PCRM_US"."NE_TCDNE" 
 ADD CONSTRAINT "FK_NE_TCDNE_NE_TDENE"
	FOREIGN KEY ("DENE_DENE") REFERENCES  "FS_PCRM_US"."NE_TDENE" ("DENE_DENE")
;

ALTER TABLE  "FS_PCRM_US"."NE_TCDNE" 
 ADD CONSTRAINT "FK_NE_TCDNE_NE_TPSNE"
	FOREIGN KEY ("PSNE_PSNE") REFERENCES  "FS_PCRM_US"."NE_TPSNE" ("PSNE_PSNE")
;